# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UD5sZ0p8OUeYmfsz_1zjnhlAlch-orPr
"""

#tipo = input('Para calcular precio de ASSESSMENT escribe "1", para FORMACIÓN escribe "2":')
tramos=[50,100,200,300,400,500,600,700,800,900,1000]
tramos_users=[50,50,100,100,100,100,100,100,100,100,100]

#Datos Assessment
ass_pricing=[10,8,8,6,6,4,4,2,2,1,1]
subtotal_ass=[]
for i in range(len(ass_pricing)):
  subtotal_ass.append(ass_pricing[i]*tramos_users[i])
agregado_ass=[]
for i in range(len(subtotal_ass)):
  if i==0:
    agregado_ass.append(subtotal_ass[i])
  else:
    sub_prob=0
    while i>=0:
      sub_prob+=subtotal_ass[i]
      i-=1
    agregado_ass.append(sub_prob)
    sub_prob=0


#Datos Formación
for_pricing=[20,16,12,8,7,5,4,2,2,1,1]
subtotal_for=[]
for i in range(len(for_pricing)):
  subtotal_for.append(for_pricing[i]*tramos_users[i])
agregado_for=[]
for i in range(len(subtotal_for)):
  if i==0:
    agregado_for.append(subtotal_for[i])
  else:
    sub_prob=0
    while i>=0:
      sub_prob+=subtotal_for[i]
      i-=1
    agregado_for.append(sub_prob)
    sub_prob=0

#Calculadora Assessment
def calculadora_ass(users:int):
  if users<50:
    return users*ass_pricing[0]
  if users<1000:
    for i in range(len(tramos)-1):
      if tramos[i]<=users<tramos[i+1]:
        posicion=i
        base=agregado_ass[i]
        resto=(users-tramos[i])*ass_pricing[i+1]
        return base+resto
  if users==1000:
    return agregado_ass[len(agregado_ass)-1]
  if users>1000:
    base=agregado_ass[len(agregado_ass)-1]
    resto=(users-1000)*3
    return base+resto

#Calculadora Formación
def calculadora_for(users:int):
  if users<50:
    return users*for_pricing[0]
  if users<1000:
    for i in range(len(tramos)-1):
      if tramos[i]<=users<tramos[i+1]:
        posicion=i
        base=agregado_for[i]
        resto=(users-tramos[i])*for_pricing[i+1]
        return base+resto
  if users==1000:
    return agregado_for[len(agregado_for)-1]
  if users>1000:
    base=agregado_for[len(agregado_for)-1]
    resto=(users-1000)*3
    return base+resto

# --- INTERFAZ STREAMLIT ---
import streamlit as st
st.title("Calculadora de Precios")

tipo = st.selectbox(
    "Selecciona tipo de cálculo",
    ("ASSESSMENT", "FORMACIÓN")
)

users = st.number_input("Introduce el número de personas", min_value=1, step=1)

entrenamiento = 7000

if st.button("Calcular"):
    if tipo == "ASSESSMENT":
        precio = calculadora_ass(users)
        st.write(f"Precio: {precio}€")
        st.write(f"Precio por usuario: {precio/users:.2f} €/usuario")
        st.write(f"Entrenamiento: {entrenamiento}€")
        st.write(f"Precio final: {precio+entrenamiento}€")
    else:
        precio = calculadora_for(users)
        st.write(f"Precio (mensual): {precio}€")
        st.write(f"Precio por usuario: {precio/users:.2f} €/usuario")
        st.write(f"Entrenamiento: {entrenamiento}€")
        st.write(f"Precio primer mes: {precio+entrenamiento}€")
